apiVersion: v1
kind: ReplicationController
metadata:
  name: repctrller
  namespace: non-certs
spec:
  replicas: 3
  selector:
    createdBy: bright
  template: 
    metadata:
      name: reptn-pod
      labels:
        name: 
      

