apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data-pvc
  namespace: devops-tools
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage 
  resources:
    requests:
      storage: 10Gi
