apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deployment2
  name: deployment2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deployment2
    spec:
      containers:
      - image: httpd
        name: httpd
        resources: {}
status: {}
