apiVersion: v1
kind: Pod
metadata:
  name: pod-two
  namespace: ns-one
  labels:
    use: feb23-k8s
spec:
  containers:
    - name: busybox
      image: radial/busyboxplus:curl
      command: ['sh', '-c', 'while true; do sleep 3600; done']
