apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ns-one
  name: pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/logs"]
    verbs: ["get", "watch", "list"]
