apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ns-one
  name: sa-pod-reader
subjects:
  - kind: ServiceAccount
    name: svcac1
    namespace: ns-one
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io  
