apiVersion: v1
kind: Pod
metadata:
   name: env
   labels:
     createdBy: Teargazz
     env: Prod
spec:
  containers:
    - name: env-test
      image: httpd
      env:
        - name: Flavor
          value: cent8
        - name: version
          value: '8.0'
