apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
  namespace: cka
spec:
  containers:
    - name: busybox
      image: busybox:latest
      command: ['sh', '-c', 'while true; do sleep 36000; done']
      livenessProbe:
        exec:
          command: ["echo", "Hello, World!"]
        initialDelaySeconds: 5
        periodSeconds: 5
