apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: cka
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bright
  template:
    metadata:
      labels:
        app: bright
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 80
