apiVersion: v1
kind: Pod
metadata:
  name: onfailure-pod
  namespace: cka
spec:
  restartPolicy: OnFailure
  containers:
    - name: busybox
      image: busybox:latest
      command: ['sh', '-c', 'sleep 10; yjf[fk a']
