apiVersion: v1
kind: Pod
metadata:
  name: always-pod
  namespace: cka
spec:
  restartPolicy: Always
  containers:
    - name: busybox
      image: busybox:latest
      command: ['sh', '-c', 'sleep 10']
