apiVersion: v1
kind: Pod
metadata:
  name: request-limits
  namespace: cka
spec:
  containers:
    - name: busybox
      image: busybox:latest
      command: ['sh', '-c', 'while true; do sleep 36000; done']
      resources:
        requests:
          cpu: "250m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"
