apiVersion: v1
kind: Pod
metadata:
  name: request
  namespace: cka
spec:
  containers:
    - name: busybox
      image: busybox:latest
      command: ['sh', '-c', 'while true; do sleep 36000; done']
      resources:
        requests:
          cpu: "100000m"
          memory: "128Mi"
