apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-pod-reader
subjects:
  - kind: ServiceAccount
    name: brightsa
    namespace: cka
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
