apiVersion: v1
kind: Pod
metadata:
  name: vol-pod
  namespace: cka
  labels:
    CreatedBy: Bright
    purpose: cka-prep
spec:
  containers:
    - name: busybox
      image: busybox:latest
      command: ['sh', '-c', 'while true; do sleep 3600; done']
      volumeMounts:
        - name: configmap-vol
          mountPath: /etc/config/configmap
        - name: secret-vol
          mountPath: /etc/config/secret
  volumes:
    - name: configmap-vol
      configMap:
        name: my-configMap
    - name: secret-vol
      secret:
        secretName: my-secret
