apiVersion: v1
kind: Pod
metadata:
  name: vol-pod
  namespace: ns-one
spec:
  containers: 
    - name: cont1
      image: busybox
      command: ['sh', '-c', 'while true; do sleep 3600; done']
      volumeMounts:
        - name: cfgmp-vol
          mountPath: /etc/config/cfgmap

        - name: seq-vol
          mountPath: /etc/config/secret
  volumes:
    - name: cfgmp-vol
      configMap:
        name: cfgmap1

    - name: seq-vol
      secret:
        secretName: sekret1
